acceptance/controllers tests
Caveman21days/ror_tnk pull request #3
Opened 2018-03-21 11:22 UTC by Caveman21days

2018-03-21 12:53 UTC, vkurennov requested changes

2018-03-21 12:53 UTC, vkurennov commented on .rake_tasks~
> +about
Удали все временные файлы, которые создаеть твой редактор. Это мусор, которого не должно быть в репозитории. и добавь в .gitignore строку вида:

`*~`

чтобы больше такие файлы git не учитывал

2018-03-21 12:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def index
У нас список ответов должен быть на стнанице вопроса, потому index для ответов не нужен в принципе

2018-03-21 12:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to @question
Плохое решение. Так ты потеряешь информацию об ошибках валидации и все то, что пользователь уже ввел. Отображение флеш-сообщения об ошибке не достаточно: нужно написать, что конкретно не так и дать пользователю возможность исправить ошибку, не набирая все заново.

2018-03-21 12:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.id == @answer.user_id
Сравнение верное, но  оно нам еще не раз потребуется, поэтому лучше его вынести в метод `User#author_of?` и использовать этот метод, где нужно

2018-03-21 12:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      flash[:danger] = 'You do not own the answer!'
А в этом случае какой рендер/редирект? Рендерить вид destroy тут не верно (а это будет по-умолчанию)

2018-03-21 12:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :question_id, :user_id)
`:question_id` приходит в url, а не в параметрах формы, а `:user_id` мы берем из current_user, поэтому тут оба эти параметра не нужны

2018-03-21 12:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
>      @answer = @question.answers.new(answer_params)
Тут еще должна быть связь с залогиненным юзером. Причем именно через current_user, а не через параметры формы, т.к. тогда можно передать любой user_id

2018-03-21 12:53 UTC, vkurennov commented on app/controllers/questions_controller.rb
>      @question = Question.new(question_params)
Нужна связь с `current_user`

2018-03-21 12:53 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user.id == @question.user_id
Замени на вызов `User#author_of?`

2018-03-21 12:53 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      flash[:notice] = 'Something gone wrong'
Что рендерим в этом случае?

2018-03-21 12:53 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :user_id)
user_id не должен передаваться в параметрах формы, мы берем его из current_user

2018-03-21 12:53 UTC, vkurennov commented on app/views/questions/index.html.haml
> +  - if current_user && current_user.id == q.user_id
Замени на вызов `User#author_of?`

2018-03-21 12:53 UTC, vkurennov commented on app/views/questions/new.html.haml
> += form_for @question do |f|
Здесь нужен вывод ошибко валидации (и это надо делать не через флеш-сообщение)

2018-03-21 12:53 UTC, vkurennov commented on app/views/questions/new.html.haml
> +  = f.hidden_field :user_id, value: current_user.id
Если я открою код формы и подставлю сюда любое значение, то легко создам вопрос от другого пользователя. Никогда не связывай объект с пользователем через скрытое поле - это большая дыра в безопасности. У тебя в контроллере для этого есть `current_user`

2018-03-21 12:53 UTC, vkurennov commented on app/views/questions/show.html.haml
> +      - if a.user == current_user
Во-первых, сравнивать надо по id, чтобы не тянуть из базы ассоциированный объект, как ты это и делал ранее. Во-вторых, замени на вызов `User#author_of?`

2018-03-21 12:53 UTC, vkurennov commented on app/views/questions/show.html.haml
> +  = form_for [@question, @answer] do |f|
Тут нужен вывод ошибок валидации

2018-03-21 12:53 UTC, vkurennov commented on app/views/questions/show.html.haml
> +    = f.hidden_field :user_id, value: current_user.id
Не используй поле формы для связи с current_user

2018-03-21 12:53 UTC, vkurennov commented on db/migrate/20180319161322_add_user_id_to_answers_and_questions.rb
> +    add_reference :questions, :user, index: true
В 5-х рельсах опция `index: true` включена по-умолчанию, ее можно не указывать. А вот опцию `foreign_key: true` указать стоит, чтобы включить контроль целостности на уровне БД

2018-03-21 12:53 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created'
Нужно еще проверит, что заголовок и тело ответа появились на странице

2018-03-21 12:53 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +feature 'Create question page' do
1. Не нужно указывать слово "page" в названии фичи. Мы не страницы тестируем, а в целом реализацию фичи, она может включать в себя несколько страниц
2. Нужен сценарий на невалидный вопрос - проверить, что выводятся ошибки валидации

2018-03-21 12:53 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +feature 'Create question page' do
Файл называется delete_question_spec.rb, а в описании - Create. Когда копируешь код, то внимательно смотри, что нужно менять, вряд ли нужна точная копия

2018-03-21 12:53 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +    visit questions_path
Не нужно повторять шаги для создания вопроса, это будет замедлять тест и не влияет на проверку удаления. Поэтому лучше создать вопрос через фабрики.

2018-03-21 12:53 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +  scenario 'authenticated user creating question' do
Меняй названия сценариев, чтобы они соответсвовали тому, что в них тестируется

2018-03-21 12:53 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created'
Это уже протестировано в другом тесте, зачем тут дублировать тест?

2018-03-21 12:53 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +    expect(page).to have_content 'Question successfully deleted!'
Нужно проверить, что этого вопроса больше нет на старнице

2018-03-21 12:53 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +  scenario 'non-authenticated user creating question' do
1. Название сценария не соответсвует содержанию
2. Нужен похожий сценарий для залогиненного юзера, который не является автором

2018-03-21 12:53 UTC, vkurennov commented on spec/acceptance/index_question_page_spec.rb
> +    questions
Чтобы не приходилось вызывать метод для создания данных, можно его объявить через `given!/let!`, тогда он будет выполняться перед каждым тестом, а не в момент первого вызова.

2018-03-21 12:53 UTC, vkurennov commented on spec/acceptance/show_question_page_spec.rb
> +  scenario 'authenticated user can see, create and delete(his own answers) answers of question' do
Это не просто 3 разных сценария, это еще и 3 разных фичи и тестировать их нужно в отдельных файлах. Раздели сценарии и фичи

2018-03-21 12:53 UTC, vkurennov commented on spec/acceptance/show_question_page_spec.rb
> +    expect(question_answers.answers.size).to eq 2
Нет, в acceptence-тестах мы не можем ничего проверять через базу, только через страницу и то, с чем может взаимодействовать юзер. Т.е. тут надо проверить, что ответ был на странцие, потом удалить и проверить, что его больше нет на странице

2018-03-21 12:53 UTC, vkurennov commented on spec/acceptance/show_question_page_spec.rb
> +  scenario 'non-authenticated user can see but cant create answers answer for the question' do
Это опять же разные сценарии

2018-03-21 12:53 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  # describe 'GET #show' do
Удаляй закомментированный код, нечего хранить хлам в репозитории

2018-03-21 12:53 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer: attributes_for(:answer, user_id: @user.id) } }.to change(question.answers, :count).by(1)
user_id не должен передаваться в параметрах ответа

2018-03-21 12:53 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'with valid attributes' do
Нужен тест на то, что ответ связывается с залогиненным юзером

2018-03-21 12:53 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        post :create, params: { question_id: question, answer: attributes_for(:answer, user_id: @user.id) }
user_id не должен передаваться в параметрах ответа

2018-03-21 12:53 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to have_http_status(204)
Так редирект, как сказано в описании теста или стаус 204? Кроме того, статус не отменяет рендера. По-умолчанию, контроллер отрендерит одноименный вид, т.е. destroy, но т.к. его нет, то будет ошибка.

2018-03-21 12:53 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:question, user_id: @user) } }.to change(Question, :count).by(1)
user_id не должен передаваться в параметрах ответа

2018-03-21 12:53 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>        it 'should saves new question in the db' do
Нужен тест проверяющий, что вопрос связывается с залогиненным юзером

2018-03-21 12:53 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        post :create, params: { question: attributes_for(:question, user_id: @user) }
user_id не должен передаваться в параметрах ответа

2018-03-21 12:53 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect(response).to have_http_status(204)
И какой вид при этом рендерится?

2018-03-21 13:43 UTC, Caveman21days commented on app/controllers/answers_controller.rb
>      @answer = @question.answers.new(answer_params)
про это позабыл совсем

2018-03-21 13:44 UTC, Caveman21days commented on app/views/questions/new.html.haml
> +  = f.hidden_field :user_id, value: current_user.id
я про current_user у devise прочитал уже потом и много мелких косяков оставил именно поэтому

2018-03-21 13:48 UTC, Caveman21days commented on spec/controllers/answers_controller_spec.rb
> +        post :create, params: { question_id: question, answer: attributes_for(:answer, user_id: @user.id) }
а как мне его передать именно для залогиненного юзера?

2018-03-23 07:23 UTC, vkurennov requested changes

2018-03-23 07:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if user_signed_in?
Это лишнее, у тебя в контроллере стоит фильтр `authenticate_user!`, т.е. управление в экшн перейдет только если юзер аутентифицирован, в противном случае, devise сделает редирект на страницу логина

2018-03-23 07:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @answer = Answer.new(answer_params.merge({ user_id: current_user.id, question_id: @question.id }))
Используй создание через ассоциации хотя бы с одним объектом, а второй можно уже через merge добавить. При этом связывать надо не по id, а по обхектам, с id рельсы сами разберутся. Т.е. писать надо `user: current_user` и короче и в объектном стиле.

2018-03-23 07:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +        flash[:danger] = @answer.errors.full_messages
Плохое решение. Я писал, что выводить ошибки надо не через флеш-сообщения. Флеш-сообщения для другого. А вывод ошибок надо сделать прямо в форме (т.е. на уровне видов).

2018-03-23 07:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if user_signed_in?
Опять  лишняя проверка

2018-03-23 07:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +        flash[:danger] = @answer.errors.full_messages
При удалении не проводится валидации, поэтому тут всегда будет пусто. Лучше вывести сообщение о том, что удалить ответ не удалось

2018-03-23 07:23 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    else
Не дублируй работу девайса, он все это уже делает за тебя.

2018-03-23 07:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    unless current_user.nil?
Лучше if current_user и в постфиксной форме, т.к. в теле всего одна строка.

2018-03-23 07:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    unless current_user.nil?
Лишнее

2018-03-23 07:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      @question = Question.new(question_params)
Горзадо лучше сделать это через ассоциации:  `@question = current_user.questions.new(...)`

2018-03-23 07:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +        flash[:danger] = @question.errors.full_messages
Выводи ошибки в форме, а не через флеш-сообщения

2018-03-23 07:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if user_signed_in?
Лишнее

2018-03-23 07:23 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +        flash[:danger] = @question.errors.full_messages
см. замечание к `AnswersController#destroy`

2018-03-23 07:23 UTC, vkurennov commented on app/models/user.rb
> +
зачем тут пустые строки?

2018-03-23 07:23 UTC, vkurennov commented on app/views/questions/new.html.haml
> += form_for @question do |f|
Прочитай еще раз замечание выше

2018-03-23 07:23 UTC, vkurennov commented on app/views/questions/show.html.haml
> +  = form_for [@question, @answer] do |f|
Тут также нужен вывод ошибок валидации, но не через флеш

2018-03-23 07:23 UTC, vkurennov commented on spec/acceptance/answer/create_answer_spec.rb
> +    expect(page).to have_content question_answers.answers[0].body
это не относится к фиче создания ответа

2018-03-23 07:23 UTC, vkurennov commented on spec/acceptance/answer/create_answer_spec.rb
> +feature 'show question answers create' do
где тест на вывод ошибок валидации?

2018-03-23 07:23 UTC, vkurennov commented on spec/acceptance/answer/delete_answer_spec.rb
> +feature 'show question answers delete' do
одна фича должна тестироваться, тут в описании 2 или даже больше

2018-03-23 07:23 UTC, vkurennov commented on spec/acceptance/answer/delete_answer_spec.rb
> +    expect(page).to_not have_content 'MyAnswer_7'
Тогда до удаления и надо проверять наличие MyAnswer_7 на странице.

2018-03-23 07:23 UTC, vkurennov commented on spec/acceptance/question/create_question_spec.rb
> +    expect(page).to have_content 'Test question'
А проверка тела?

2018-03-23 12:49 UTC, vkurennov requested changes

2018-03-23 12:49 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user
А постфиксная форма где?

`@answer = Answer.new if current_user`

2018-03-23 12:49 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).user_id).to eq @user.id
в юнит-тестах действует правило "один тест - один expect", так что нужно это выделить в отдельный тест

2018-03-23 12:49 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect(assigns(:question).user_id).to eq @user.id
Выдели в отдельный тест

2018-03-23 12:49 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User do
А где тесты на метод `author_of?`, любой код, который ты пишешь, должен быть протестирован.

2018-03-23 14:37 UTC, vkurennov approved these changes

2018-03-23 14:37 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.author_of?(answer)).to be_falsey
rspec определяет динамические метчеры (методы для проверки) для методов-предикатов (это методы, которые заканчиваются на знак вопроса и возвращают true/false) и можно писать короче и красивее:
`expect(user).to be_author_of(answer)`

2018-03-23 14:37 UTC, vkurennov commented on spec/models/user_spec.rb
> +    it 'When user is not owner of question its falsey' do
Не нужно проверть на ответе. У тебя же универсальный метод, он вообще не зависит от типа объекта, лишь бы у него был user_id. Так что достаточно проверить на любом объекте с таким методом.

2018-03-26 06:09 UTC, merged